name: Tests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage

      - name: Run tests
        run: |
          pytest --cov=app test_app.py

      - name: Check code coverage
        run: |
          coverage report
          coverage html

      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov
